### ISSUE TITLE
"Discover Store" Is an unexplained thing in the FAQ

### ISSUE THREAD

**Issue by Routhinator** [goatcorp/FFXIVQuickLauncher#1156]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I went to the FAQ and dug through issues, and cannot find any explanation of what a "Discover Store" is. I cannot find a direct link to the Linux Binary either as all the FAQs just say 'search the discover store'.

From what I can tell "Discover Store" is a KDE thing. As a Linux User running a Ubuntu Gnome desktop - I do not want to pollute my ecosystem with KDE libs. 

The FAQ needs to cover that this is a KDE/SteamOS only thing and provide a link to directly download the binary for other flavours of Linux.

### Platform

Linux (native)

### Wine/Proton runner version

No Idea. Can't find the download.

**Comment by NotNite** [comment]
The Discover store is a frontend for Flatpaks. We could definitely change this - you're correct, it was written in mind for Steam Deck users, where the desktop environment is KDE.

You can use your favorite desktop's GUI frontend for Flatpaks, or install it from the CLI: `flatpak install flathub dev.goats.xivlauncher`

There's unofficial Ubuntu PPAs/an MPR repository made by the community, but we don't cover them on the website because they're not official and we can't 100% vouch for the safety of them. If you're interested in those installation methods, they're pinned in our Discord server (sorry, I know how frustrating it is to have to join a Discord server to find gated information, I'll definitely bring this up with the team).

Could you move this to the goatcorp/faq repo? Better place to track a revision IMO.

**Comment by Routhinator** [comment]
https://github.com/goatcorp/faq/issues/73 is opened.
