### ISSUE TITLE
How can I use my own config file since xivLauncher on linux starts the game with default settings.

### ISSUE THREAD

**Issue by sainishwanth** [goatcorp/FFXIVQuickLauncher#1251]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I'm currently using XIVLauncher from an AUR package (I've had the same issue with the flatpak too), It starts the game with default settings (res, HUD, etc). I'd like to use my usual configuration or have it use my FFXIV.conf file which has all my settings stored.

Any help is appreciated, thanks :)

### Platform

Linux (native)

**Comment by tjlauer** [comment]
bruh, closed with no explanation... shame

**Comment by reiichi001** [comment]
> bruh, closed with no explanation... shame

What possessed you to comment on a closed issue from 3 years ago?

Please refer to our FAQ posts on migrating config across platforms. https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-migrate-ffxiv-andor-xivlauncher-files-from-an-old-wine-prefix-to-a-new-one-linux

**Comment by anto77562** [comment]
Maybe because this would be a helpful question to have answered? I'm also looking for the answer to this.

I saw this as a search result on Google and went "oh! That's the exact question I have!"  And then when I clicked on it to find the answer I was greeted with 2 comments. On lamenting the fact that the question was never answered, and someone else being hostile that anyone would still want the question to be answered.

There could at least be a not saying *why* there isn't/won't be an answer rather than nothing at all.

**Comment by reiichi001** [comment]
Did you try clicking the link in my prior comment? It is quite literally the answer. 

This particular repository is for the wi does version of xivlauncher. We have a separate one for Linux users, in addition to the FAQ and discord for support. 

Typically, when the user closes their issue, that means they self-solved, found the answer, or didn't need it answered anymore. 

I encourage you to check our migration faq. I'm pretty sure it covers this. I'm the one who wrote it. 

You can also just set a custom game config path I xivlauncher.core's settings too.

**Comment by anto77562** [comment]
Hmmm.. maybe I need a lesson in reading because I seem to have completely overlooked that part of the comment, and then made an ass of myself. Sorry for being so rude.
