### ISSUE TITLE
Opening the launcher (from flatpack) causes windown manager to crash

### ISSUE THREAD

**Issue by Mirino97** [goatcorp/FFXIVQuickLauncher#1541]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I haven't opened ffxivlauncher for a few months, waiting for DT to release. 
Heard it was possible to pre-download DT, so I decided to get ready.

Ran ``flatpack update dev.goats.xivlauncher``, updates normally.

Now when I open it, all windows have their respective window manager borders flicker on and off, freezing the computer between flickers untill I either reset the computer or ctrl+c the console.

I'm on Arch (Garuda), with x11.

There are no errors in the console, so I'm stumped, and grasping at straws.

### Platform

Linux (native)

**Comment by rankynbass** [comment]
You should probably open the issue on the XL.Core repo: https://github.com/goatcorp/XIVLauncher.Core/issues. That said, since you're on Garuda, you can try installing the native package from the aur. `paru xivlauncher` or `yay xivlauncher`, whichever Garuda uses. Install xivlauncher 1:1.0.8-2 or xivlauncher-bin 1.0.8-1.

**Comment by Mirino97** [comment]
Oh, great catch. I failed to notice a native package already exists.

Still, the problem persists. I'll move this issue over to XL.Core, thank you very much!
