### ISSUE TITLE
Option to disable check for administrator priviliges

### ISSUE THREAD

**Issue by TrContact** [goatcorp/FFXIVQuickLauncher#303]
The dialog that pops up every time I start XIVLauncher warning me that it/the game is set to launch as administrator is honestly in the way. While I respect XIVLauncher's opinion, in my use case there is no "issue" to "automatically fix" and all it's doing is nagging me about something I am literally never going to change.

**Comment by Caraxi** [comment]
my only question is why are you running it as admin

**Comment by legluondunet** [comment]
I have the same error when I launch it with wine, very annoying.
Please could you disable administrator check if XIVLauncher launch with wine?

**Comment by goaaats** [comment]
With wine that's legit, will be adding this.

**Comment by oslerw** [comment]
I'm also interested in this for running on Wine, so I tried to look at it.

This error is coming directly from Squirrel. Specifically, it checks for admin, tries to re-run itself with reduced privileges if it finds it, then produces the error if it's still admin.

Relevant code: https://github.com/Squirrel/Squirrel.Windows/blob/76c87af6f389bea69576c738ef46574b2945b0ba/src/Setup/winmain.cpp#L78

If I'm reading this right, what needs to happen is adding a configuration to Squirrel that allows you to disable this, then setting the config in XIVLauncher.

**Comment by mephitisdeux** [comment]
I too would like to get this working in Win.e Install fails instantly on the "running in administrator mode" message.  Apparently some can run this on Wine without issue, but I've yet to see details on how. Will update if I do.

**Comment by reiichi001** [comment]
Wine users can set an environment variable for `XL_WINEONLINUX=true` (ideally in Lutris on your game config) which will silence the "don't run this as admin" nag on Linux. It also disables a few other generally windows-specific checks (although Wine should satisfy them too).

The majority of Wine users shouldn't be running into installation failures outside of winetricks failing to install vcrun2019 because of hashing errors, which is unrelated to this check.

**Comment by mephitisdeux** [comment]
> Wine users can set an environment variable for `XL_WINEONLINUX=true` (ideally in Lutris on your game config) which will silence the "don't run this as admin" nag on Linux. It also disables a few other generally windows-specific checks (although Wine should satisfy them too).
> 
> The majority of Wine users shouldn't be running into installation failures outside of winetricks failing to install vcrun2019 because of hashing errors, which is unrelated to this check.

Yeah, exporting that envar doesn't work for me, sadly. All I get is this in the terminal.
```
00b4:fixme:ieframe:DllGetClassObject {9ba05972-f6a8-11cf-a442-00a0c90a8f39} {00000001-0000-0000-c000-000000000046} 0032DC98
00b4:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll"
00b4:fixme:ver:GetCurrentPackageId (0032FE94 00000000): stub
```
...with the "Please re-run this installer as a user instead of administrator" dialog. Is there a way to manually install it? I do not use Lutris. The game's old launcher runs fine, and the game itself gives no issues, but I have never been able to set up XIVLauncher.

System info:
**OS**: Arch Linux (Linux 5.12.14-arch1-1)
**Wine**: 6.12 (with DXVK and wine-timing lsmod)

**Comment by goaaats** [comment]
That must be a Squirrel thing and not our fault, so you're talking about something entirely different to Franz.
Try ``wine runas /trustlevel:0x20000 Setup.exe``.

https://bugs.winehq.org/show_bug.cgi?id=40613

**Comment by mephitisdeux** [comment]
> wine runas /trustlevel:0x20000 Setup.exe

Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

```
[atsuko]~/Downloads$ 00d4:fixme:netprofm:connection_point_Advise 007C9028, 00E3F2FC, 00E3F364 - semi-stub
00d4:fixme:netprofm:list_manager_GetConnectivity 007C9008, 01E9FBA0
```
I had read somewhere that runas had been broken or depreciated. Is there no way to run port ably, as in without the installer?

**Comment by goaaats** [comment]
Sure, but you won't get auto-updates. I'm not sure which wine runner you are on, but this works fine in the one we specify for Lutris.

Download the artifact from here: https://github.com/goatcorp/FFXIVQuickLauncher/actions/runs/962429912

**Comment by mephitisdeux** [comment]
> Sure, but you won't get auto-updates. I'm not sure which wine runner you are on, but this works fine in the one we specify for Lutris.
> 
> Download the artifact from here: https://github.com/goatcorp/FFXIVQuickLauncher/actions/runs/962429912

Well the good news, is it's not complaining I don't have .NET 4.7.2 which apparently can't install in the latest Wine, or isn't working, so it's no longer an issue on your end.

To answer your question, though, I'm not using a runner. Stock wine with DXVK overrides. I don't use Proton outside of Steam, or Lutris at all. Stock prefix works fine with FFXIV, Origin, GOG games, etc.

**Comment by mephitisdeux** [comment]
Update. Was able to force-install .NET 4.8, so the unsupported artifact snapshot works fine. The release Setup file still throws the admin issue, though.

**Comment by andreycout** [comment]
I will second the request for an option to remove this notification. I run XIVL as admin on Windows because I run Steam as admin, reason being that I use SteamInput as my main source of input for my Living Room PC setup. Without admin, controller will freeze when any elevated prompt pops up (task manager for example). Also, I use Steam to launch Ashita/FFXIEden, which requires admin. If Steam isn't running on admin as well, controller will not work on the game.

When I launch XIVLauncher without admin, Steam Overlay doesn't hook to the game, I can't change controller configuration through the overlay, Steam doesn't log my hours and my friends can't see I'm playing FFXIV.

All in all, just an option to disable the warning would be great. I don't care that it might break some plugins, I just want to select XIVL shortcut and go straight to the game, that's my main use for it.

**Comment by reiichi001** [comment]
@andreycout if you want to run things the wrong way on purpose, just go all the way and disable UAC prompts while you're at it. 

All you've really provided is further proof of why we don't recommend running things as admin, because it sets off a chain of having to run other programs as admin to fix up fucked up permissions. We have moved on from Windows XP.

This issue was specific to wine users, who don't get the option to launch as not-Administrator. They get special treatment. Windows users are responsible for setting up their machines appropriately or dealing with being reminded that they didn't.
