### ISSUE TITLE
same error again and again.

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [goatcorp/FFXIVQuickLauncher#321]
Hello, still getting this error again and again. I don't understand. I've uninstalled XIVlauncher then reinstall it back but the error still continue. I've fix this before 5.4 by rebooting my system but now it doesn't work anymore.

**Comment by HitagiSenjougaharaFFXIV** [comment]
System.Exception: Game exited prematurely
   à XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) dans D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:ligne 255
Version: 5.2.0.0
Git Hash: 7f46f54
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: French
LauncherLanguage: French
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []

**Comment by HitagiSenjougaharaFFXIV** [comment]
i've uninstall gshade and it works

**Comment by HitagiSenjougaharaFFXIV** [comment]
so basically, there's an issue with reshade... if you can fix that thx

**Comment by reiichi001** [comment]
Hi there!

It's probably not actually gshade/reshade's fault. Plugins that were supposed to be disabled were not, and they've mostly been what's causing crashes.

It may help to install gshade/reshade in d3d11 mode instead of dxgi as well. If you already have, then switch it. (This seems to be dependent on other installed files on the computer and is harder to track down the root cause.)

Please try this:
1. Close the game
2. Go to `%AppData%\XIVLauncher\installedPlugins`
3. Remove all plugin folders.
4. Go to ``%AppData%\XIVLauncher`
5. Remove the Addon folder.
6. Relaunch
7. Let us know if the issue persists

**Comment by HitagiSenjougaharaFFXIV** [comment]
Hi, i've reinstalled gshade in d3d11 mode instead of dxgi. I did :

   1. Close the game
   2. Go to %AppData%\XIVLauncher\installedPlugins
   3. Remove all plugin folders.
   4. Go to ``%AppData%\XIVLauncher`
   5. Remove the Addon folder.
   6. Relaunch
   7. And same error
   8. I remove gshade
   9. It works

System.Exception: Game exited prematurely
   à XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region,
Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean
isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath,
Boolean isDx11, ClientLanguage language, Boolean encryptArguments) dans
D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:ligne 255
Version: 5.2.0.0
Git Hash: 7f46f54
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: French
LauncherLanguage: French
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm
Reborn


Addons: []
