### ISSUE TITLE
/xlsettings command does nothing?

### ISSUE THREAD

**Issue by Orgoreyn** [goatcorp/FFXIVQuickLauncher#371]
When I launch the game through quicklauncher, I can run certain commands like /xlhelp and /xllanguage, but not /xlsettings. This means I can't install or use certain plugins. I type in /xlsettings, hit enter, and then nothing happens. **[See here for a video of the issue in action.](https://drive.google.com/file/d/1rPaefVrhpdhyEacsEjrKqROZXyCv14mf/view?usp=sharing)** Am I missing something?

**Comment by Zyian** [comment]
Installing plugins is found under `xlplugins`

**Comment by reiichi001** [comment]
hello! 

It sounds like another program on your computer may be conflicting with the in-game addon system's GUI. This can be easier troubleshot in the discord, but here's a copy of our FAQ on this from there.

**The in-game addon (Dalamud) and/or plugins doesn't work or don't display**

Like many other game tools, Dalamud works by injecting into the FFXIV process and hooking DirectX. Occasionally, it conflicts with other tools or can't work because of them.

Some of the more common ones that may cause issues are:
- **Common Third-Party Antivirus** programs. See the dedicated FAQ for this using `f!faq av`
- **MacType **(makes no changes to FFXIV because it doesn't use normal fonts anyways. Block it from hooking to FFXIV and you'll be fine.)
- **MSI Afterburner** (contains RTSS. See below.)
-  **OBS **(Some of the streaming modes involve hooking directx for better capture. This can cause plugins to render in streams or to not render at all. You may need to change your capture methods.)
- **RivaTuner**/**RTSS **(see if disabled the RTSS overlay helps. If not, blacklist FFXIV from automatic hooking. RTSS can be used after Dalamud loads without issues).

---

It may also help to upload your `dalamud.txt` log from `%appdata%\XIVLauncher\addon\Hooks\`

**Comment by Aida-Enna** [comment]
Gonna assume this was solved - Feel free to open another issue if not.
