### ISSUE TITLE
Launcher using different drive for temporary files resulting in out of space errors without prior warning

### ISSUE THREAD

**Issue by Ihysoal** [goatcorp/FFXIVQuickLauncher#380]
**Describe the bug here:**
It seems that the launcher by default is downloading all the patch files to AppData (and sporadically cleans some of it up?) without regard for space.
This resulted in multiple app crashes as it kept hitting the limit of the 20GB free space on it when I had a perfectly fine installation folder with 160 GB of space available and where it's installing to. It also just causes unnecessary writes on another SSD, not that I'm concerned about this killing lifespan.

As I was writing this bug report and restarting for the fourth time the application finally notified me that the disk was full and I could change the patch folder, something I hadn't noticed myself. I'm not sure if the option presented itself during setup or that I missed it. In case I missed it then I'm a dummy. However, it still crashed on me instead of stopping me more gracefully.

**Steps to reproduce the bug:**
- Have not enough disk space on the drive that the user's AppData folder is on, typically C:
- Install to another disk (in my case: F:\Games\FINAL FANTASY XIV - A Realm Reborn)
- No warnings about disk space
- Application crashes when it inevitably runs out of space to write
- Practice your ad pop-up closing skills by closing a multitude of error prompts.

**Expected behavior**
- Warn the user about not enough download folder space.
- Download to the installation folder by default or a specified download folder during installation.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 Pro
  XIVLauncher version: 5.2.4
  Launching as admin?: No
  Using Steam?: Nope
  Addons/Plugins enabled: Ixnay

**Additional information**
Also, it seems to download to AppData/Roaming by default which is _technically_ a big no-no as that folder is meant for important configuration data that, well, roams between multiple PCs following the user's account on a domain. Although I doubt many people will be installing it in such an environment...

Edit: Small theory: issue only cropped up because download speed exceeded installation/unpacking speed.

**Comment by reiichi001** [comment]
You can change the path that patch downloads are saved to in the xivlauncher settings. 

It also sounds like you did not set your game path correctly if XIVLauncher is trying to fully reinstall the client. I've copied our FAQ from Discord on this topic, as it will likely help.

**Where can I find my FFXIV Installation?**
(AKA: What does XIVLauncher mean by GamePath?)

FFXIV installs to a few different locations depending on whether you used the official installer or steam, when you installed it, and potentionally if you installed the free trial or not. Here are some of the common paths.

Whatever you do, DO NOT SELECT THE `BOOT` OR `GAME` FOLDER. But if you already have a copy of FFXIV installed, you'll want the folder that contains them.

Official Launcher:
```C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn```

Steam:
```C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online```
```C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV - A Realm Reborn```
__NOTE__: If your steam library is on another drive, it will have a different, but similar structure.

**Comment by Ihysoal** [comment]
> You can change the path that patch downloads are saved to in the xivlauncher settings.

> As I was writing this bug report and restarting for the fourth time the application finally notified me that the disk was full and I could change the patch folder, something I hadn't noticed myself.

> It also sounds like you did not set your game path correctly if XIVLauncher is trying to fully reinstall the client. I've copied our FAQ from Discord on this topic, as it will likely help.

Correct, while FFXIV was technically installed, all the data files were deleted. I was happy to see it had no problems downloading it all for me.

**Comment by reiichi001** [comment]
XIVLauncher will never delete a currently-existing FFXIV installation. It will however, assume a default installation location for you, so if you've installed/moved it to another drive, you do have set it accordingly. Otherwise, XIVLauncher will assume that you intend for it to download the entire game again for you.

When that's the case, XIVLauncher also defaults to not keeping patch files after it has applied them, so you really only need about 5 GB of temporary space for 1-4 patches + the size of a full FFXIV install, if on the same drive. 

--

Ideally, yes, XIVLauncher should check for disk space before attempting a download. It is on the user to select their directories appropriately if they aren't in default locations or on C: though.

**Comment by Ihysoal** [comment]
Where did I say it "deletes a currently-existing FFXIV installation"?

> It will however, assume a default installation location for you, so if you've installed/moved it to another drive, you do have set it accordingly.

Enough with the canned responses. I set the installation path to "F:\Games\FINAL FANTASY XIV - A Realm Reborn" as stated in my opening post, which is where the old installation folder was. The only thing that was missing was **all the files** because **I had deleted them prior, a long time ago** and I was **pleased that it had no issue redownloading them for me**

> Otherwise, XIVLauncher will assume that you intend for it to download the entire game again for you.

As per previous message. **I was happy to see it had no problems downloading it all for me.**

> When that's the case, XIVLauncher also defaults to not keeping patch files after it has applied them, so you really only need about 5 GB of temporary space for 1-4 patches + the size of a full FFXIV install, if on the same drive.

It crashed multiple times filling the 20 GB of free space with "temporary patches" so this is just straight up not true.

> Ideally, yes, XIVLauncher should check for disk space before attempting a download. It is on the user to select their directories appropriately if they aren't in default locations or on C: though.

Thank you! We're finally getting at why I decided to still open this issue! Namely even though, for the third time, that I found out that I could set a download path,  after the application crashed 3 times, warned me the 4th time I opened it, that it had no space to download because, guess what, it had 1.4 GB space left after writing that drive full, it still crashed on me 3 times prior and spat errors on me. And setup does **not** allow you to specify a download folder. You can only do that afterwards, in one of the options, after it crashes.

Are you saying it's my fault for assuming it downloads in the game folder if I only get an option to specify a game folder, and that it's not an issue it crashes during the download because it's downloading to a folder I have no knowledge of?

**Comment by NotAdam** [comment]
> Are you saying it's my fault for assuming it downloads in the game folder if I only get an option to specify a game folder, and that it's not an issue it crashes during the download because it's downloading to a folder I have no knowledge of?

lol

![image](https://user-images.githubusercontent.com/893184/107473285-88558480-6bc4-11eb-9303-6a36bf25253e.png)

**Comment by ackwell** [comment]
> Correct, while FFXIV was technically installed, all the data files were deleted. 

Right there. Might want to reconsider your tone.

**Comment by Ihysoal** [comment]
You people are experts at completely missing the point and refusing to read posts, incredible.

**Comment by NotAdam** [comment]
no u

**Comment by Ihysoal** [comment]
Might want to reconsider your tone.

**Comment by NotAdam** [comment]
![image](https://user-images.githubusercontent.com/893184/107473613-15004280-6bc5-11eb-9885-ddef56bd1919.png)

**Comment by Ihysoal** [comment]
> > Correct, while FFXIV was technically installed, all the data files were deleted.
> 
> Right there. Might want to reconsider your tone.

And where did I say XIVLauncher deleted it?
I'll admit I worded it poorly, he was correct that XIVLauncher was trying to download the whole game, which was the intent.

**Comment by reiichi001** [comment]
Please use the official launcher. We've taken your feedback that there should be a disk space check prior to downloading the patches, rather than just erroring out when the disk becomes full.

I'm not really willing to further troubleshoot with someone who's going to have an attitude when I'm trying to assist you.

Your original messages did not indicate you PURPOSELY deleted your FFXIV installation until after I'd responded with basic information.

> while FFXIV was technically installed, all the data files were deleted
This sure sounded a lot like you hadn't been the one to remove the files. My utmost apologies for the misunderstanding.

The setup may not prompt you to set a patch folder, but it absolutely lets you change the location prior to logging in. You have a customized installation directory. And you're looking for a customized patch download location as well. These are settings you can change as a user, so feel free to do that. 

XIVLauncher will download up to 4 patches at a time, usually, these complete -mostly- in order, so you'll only have about 4-5 of them. In some cases, an earlier patch may download more slowly, so later patches will be downloaded, which can take additional room. Setting your patch download elsewhere should help alleviate that issue as the patch files will be moved there before being applied. You will still want roughly 5-6GB of free space on the same disk as your user profile because intermediate patch downloads end up in `%TEMP%`.

**Comment by Ihysoal** [comment]
I wholly admit I got too 'direct' in my third post. But see it from my side when I first get a canned response that doesn't ackowledge the real issue, and in the second assume a whole lot of stuff and still doesn't acknowledge it. Even if it stemmed from a misunderstanding.

> The setup may not prompt you to set a patch folder, but it absolutely lets you change the location prior to logging in. You have a customized installation directory. And you're looking for a customized patch download location as well. These are settings you can change as a user, so feel free to do that.

Sure, but by what knowledge? I wasn't in the need to look for any sort of customized patch download location. How would I know it's downloading to some folder in AppData instead of the one prompted folder during setup? The first time it crashed with a weird out of disk space error, even though I have plenty of disk space. Only with the second time I started investigating why it crashed. I did end up finding where it was writing to by other means. But at which point should I have known there was a way to set the download folder?

Look, it's not alien to me that launchers often provide the option to a download path, but they almost always prompt you for it. And they most certainly do not just start downloading at the download path without space, and they most most certainly do not throw exceptions at you and crash the moment it runs out of space.

> XIVLauncher will download up to 4 patches at a time, usually, these complete -mostly- in order, so you'll only have about 4-5 of them. In some cases, an earlier patch may download more slowly, so later patches will be downloaded, which can take additional room. Setting your patch download elsewhere should help alleviate that issue as the patch files will be moved there before being applied. You will still want roughly 5-6GB of free space on the same disk as your user profile because intermediate patch downloads end up in %TEMP%.

I don't see why they would need to go to a temp folder first if there's a perfectly fine specified patch location.

**Comment by reiichi001** [comment]
Please understand that I provide FREE support to hundred of xivlauncher users in addition to other discords I'm in. I've also got a professional customer service background and that is my general typing style when doing something that's basically customer service. Unless you'd prefer I answer in sass and memes like above, which just leads to making you and me both pissed off.

There are many better ways to respond to something than griping that the free support being provided by the community returned a vague answer for a vague question/response.

We've already established that there could be better error handling. A program exception is quite literally named that for a reason. It's an unhandled exception to the expected behavior. You likely got a few popups because the current disk space check is per-download and then per-install. We don't pre-allocate space for downloads or installations in advance.

> Sure, but by what knowledge? I wasn't in the need to look for any sort of customized patch download location.

Please understand that if you want to have a customized environment, you're going to have to check for those customizations yourself.

> Look, it's not alien to me that launchers often provide the option to a download path, but they almost always prompt you for it. And they most certainly do not just start downloading at the download path without space, and they most most certainly do not throw exceptions at you and crash the moment it runs out of space.

A lot of programs will download assets without directly telling you where they're being downloaded. Specifically, **the official FFXIV launcher is hardcoded to also download files into your user folder and provides absolutely no way to change this**. Is this a best practice? Not really, but it's also generally fair to assume the boot drive and/or user profile has a reasonable amount of free space. And yes, we do assume most people have ample disk space on the same disk as their user profile. 

> I don't see why they would need to go to a temp folder first if there's a perfectly fine specified patch location.

Because that's what our current download library does. Pretty much everything gets downloaded to %TEMP% and then moved to the correct location as specified. This too, is also fairly common behavior as not every library supports a custom scratch-disk location. I'll look into seeing if this is something ours does, but as XIVLauncher updates are pretty rare, it likely won't be grouped into a release until there are enough changes to warrant a new release.

**Comment by Ihysoal** [comment]
Please understand that I also provided a FREE bug report. And I know what exceptions are, thank you.

> Is this a best practice?

Wait, Japanese devs and best practice?

> but it's also generally fair to assume the boot drive and/or user profile has a reasonable amount of free space.

Is ~10% not reasonable free space? Is it fair to assume anything about something as variable as that? 

> Because that's what our current download library does.

Yeah that's what I figured.

> There are many better ways to respond to something than griping that the free support being provided by the community returned a vague answer for a vague question/response.

Sure, I think it's funny you don't even acknowledge the troll responses though.

**Comment by reiichi001** [comment]
> Wait, Japanese devs and best practice?

We really want to play this game? Windows also defaults everything over to %TEMP% like every single web browser's temporary files and every web-based installer you run. Microsoft Outlook sure as hell doesn't prompt you where it's going to save your OST file either, but you can totally do that by going into its settings like an advanced user. 

> Is ~10% not reasonable free space? Is it fair to assume anything about something as variable as that?

Your boot drive is around 50GB in total? You've probably got bigger issues to deal with then.

> Yeah that's what I figured.

The download library we use appears to have recently added the ability to redirect download chunks to a program-specified temp directory, but also has breaking changes, so I don't see this being adjusted soon.

> Sure, I think it's funny you don't even acknowledge the troll responses though.

What point is there in giving them attention?

**Comment by Ihysoal** [comment]
> Your boot drive is around 50GB in total? You've probably got bigger issues to deal with then.

So you already forgot that it filled up 20 GB?
