### ISSUE TITLE
launcher error

### ISSUE THREAD

**Issue by kali-raijin** [goatcorp/FFXIVQuickLauncher#403]
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 259
Version: 5.3.7.0
Git Hash: e4f8d3a
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by reiichi001** [comment]
Hello! This is most likely caused by your antivirus partially removing some of the files Dalamud (the plugin system) needs. 

We pushed out some updates recently and some antivirus software hasn't liked that. You may need to check your antivirus logs/quarantine to allow files.

Please also make exceptions (or whitelist) the following folders:
 - %localappdata%\XIVLauncher
 - %localappdata%\goatsoft
 - %appdata%\XIVLauncher

If you need more information or help, please see our FAQ post on the XIVLauncher discord [here](https://discord.com/channels/581875019861328007/586590269063954432/695694479923085474) or ask in the #xivlauncher_issues channel there!
