### ISSUE TITLE
Lutris/Wine Version will not Install

### ISSUE THREAD

**Issue by SkylarDragon** [goatcorp/FFXIVQuickLauncher#464]
**Describe the bug here:**
The Lutris install will go accordingly, but after installing .NET 4.8 it will show a popup saying that "This program cannot run on Windows XP or before; it requires a later version of Windows."

**Steps to reproduce the bug:**
Run the Lutris install script from the Lutris website and leave everything on the default settings.

**Expected behavior**
I expected it to install and run with no issue.

**Screenshots**
![Error Message](https://cdn.discordapp.com/attachments/713211609841008701/858388801864859648/Screenshot_20210626_125007.png)

**Other information (*please* complete the following information):**
  Operating System: Manjaro Linux 21.0 Kernal Version 5.12.9-1-MANJARO
  XIVLauncher version: 5.5.8
  Launching as admin?: NA
  Using Steam?: Yes
  Addons/Plugins enabled: NA

**Comment by reiichi001** [comment]
This appears to be a Lutris/Wine issue where it's failing to install dotnet48, vcrun2019, and set Wine to appear as Windows 7.

I was able to replicate this in a VM, but most of the time, Lutris would just hang when trying to install .Net 4.8, which is beyond our ability to troubleshoot. (This does happen on occasion, and usually the only fix is to delete your broken prefix and try again until it works). The Lutris Discord server may have some tips and advice on how to best troubleshoot that, as I couldn't reproduce the issue when I used Ubuntu or my native PopOS install. 

Manjaro could be providing a broken package or dependency, as rolling distros are known to do on occasion. This could be also due to some issue with your system wine, and wine6 does have issues creating prefixes on occasion, especially ones that need .Net in some form.

Alternatively, you could try installing each piece manually into your prefix, but this largely defeats the purpose of using Lutris to handle the steps for you. In particular, you'd want to use winetricks to install `dotnet48 vcrun2019 win7` as that's the step that it's most likely failing on. Then adjust your hide wine settings and have Lutris launch a locally downloaded XIVLauncher setup.exe to run inside the prefix.

It should also be noted that the current Lutris installer tries to install XIVLauncher 5.5.3. (I've sent an update for their install script to bump it to 5.5.8, although that's not the cause of this issue).

**Comment by SkylarDragon** [comment]
I'm a bit stumped. I tried installing all the programs with winetricks, but I can't find any way to downgrade to 5.7-11. I tried PlayOnLinux, but it has some kind of bug which prevents me from selecting 5.7-11, plus it tried to run the setup file in admin mode, which it didn't like too much. I have no idea on what I should delete to get it working like you have, because all I've been doing was deleting the entire prefix and the running it again, with the same result.

**Comment by SkylarDragon** [comment]
I got it. All I did was change the Wine configuration to Windows 7 and then run the setup.exe again. Thank you for the help!

**Comment by SkylarDragon** [comment]
I should mention that I'm still having issues, however it has nothing to do with this thread. vcrun2019 didn't and won't install at all.

**Comment by patrick-burridge** [comment]
I'm using the lutris installer https://lutris.net/games/install/21733/view

xivlauncher manages to install and launch game to title screen without dotnet and vcrun. (system wine-mono was enough for it to limp along a bit presumably)

## winetricks dotnet48 vcrun2019
Regarding the dotnet48 and vcrun2019 problems. 
	https://forum.winehq.org/viewtopic.php?f=2&t=35030
`warning: Checksum for winetricks/vcrun2019/vc_redist.x86.exe did not match`
Lutris is packaged with an outdated version of winetricks. You can (probably) configure in the lutris gui to use system winetricks. I used cmd to launch my system winetricks gui in the correct prefix because I'm not overly familiar with winetricks..
`$ winetricks prefix=../../../games/final-fantasy-xiv-online/`
and with that I could run flawlessly the vanilla ffxivboot.exe 

However, after installing those, xivlauncher refuses to budge anymore "xivlauncher failed to check for updates." 

## Why is xivlauncher update is failing? (idk, but do have workaround)

### wine spits out three errors:
```
0042:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0042:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
```
This is some deprecated samba thing that every prefix spits out.. 100% safe to ignore


```
0038:err:winsock:WSAIoctl -> SIO_ADDRESS_LIST_CHANGE request failed with status 0x2733
```
https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaioctl
> The WSAIoctl function controls the mode of a socket.
> ...
> The WSAIoctl function is used to set or retrieve operating parameters associated with the socket, the transport protocol, or the communications subsystem.
> 
> ...
>
> Any IOCTL may block indefinitely, depending on the service provider's implementation. If the application cannot tolerate blocking in a WSAIoctl call, overlapped I/O would be advised for IOCTLs that are especially likely to block including:
> 
> SIO_ADDRESS_LIST_CHANGE
> ...

TBH I only 50% understand. seems related to the error printed in the xivlauncher logs though. 


```
wine: Call from 0x7b02cee6 to unimplemented function dssenh.dll.CPAcquireContext, aborting
```
https://github.com/wine-mirror/wine/blob/master/dlls/dssenh/main.c  something to do with encryption. Unclear if/how related.


### xivlauncher log prints:
```
2021-06-29 11:36:39.255 -04:00 [INF] Trying to set up Loc for language code en
2021-06-29 11:36:39.346 -04:00 [INF] XIVLauncher started as xivlauncher-5.5.8.0-5.5.8-0-ge76118e
2021-06-29 11:36:39.346 -04:00 [INF] Starting update check...
2021-06-29 11:36:40.160 -04:00 [ERR] Update failed
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Net.UnsafeNclNativeMethods.SafeNetHandles_SECURITY.QueryContextAttributesW(SSPIHandle& contextHandle, ContextAttribute attribute, Void* buffer)
   at System.Net.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding_SECURITY(SafeDeleteContext phContext, ContextAttribute contextAttribute, Bindings* buffer, SafeFreeContextBufferChannelBinding refHandle)
   at System.Net.SSPISecureChannelType.QueryContextChannelBinding(SafeDeleteContext phContext, ContextAttribute attribute, SafeFreeContextBufferChannelBinding& refHandle)
   at System.Net.TlsStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.Net.PooledStream.TryCloseNetworkStream(Boolean closeWithTimeout, Int32 timeout)
   at System.Net.PooledStream.CancelPendingIoAndCloseIfSafe(Boolean closeWithTimeout, Int32 timeout)
   at System.Net.PooledStream.Close(Int32 timeout)
   at System.Net.Connection.AbortSocket(Boolean isAbortState)
   at System.Net.Connection.CloseOnIdle()
   at System.Net.ConnectionGroup.DisableKeepAliveOnConnections()
   at System.Net.ServicePoint.ReleaseConnectionGroup(String connName)
   at System.Net.ServicePoint.CloseConnectionGroupHelper(String connectionGroupName, Boolean closeInternal)
   at System.Net.ServicePointManager.CloseConnectionGroups(String connectionGroupName)
   at System.Net.Http.HttpClientHandler.Dispose(Boolean disposing)
   at System.Net.Http.HttpClient.Dispose(Boolean disposing)
   at System.Net.Http.HttpMessageInvoker.Dispose()
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext() in C:\Users\ana\code\Squirrel\Squirrel.Windows\src\Squirrel\UpdateManager.Factory.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Updates.cs:line 31
```
UnsafeNclNativeMethods  
https://referencesource.microsoft.com/#system/net/System/Net/UnsafeNativeMethods.cs,23fb207da1eb2f0d,references

So it's definitely a dotnet48 problem. **Mayhaps related too to all those warnings posted about disabling antivirus** :shrug: 

### Workaround
poking around in codebase I find the environmental variable I need to set to skip update checking 
> https://github.com/goatcorp/FFXIVQuickLauncher/blob/5.5.8/XIVLauncher/Updates.cs
```
#if !XL_NOAUTOUPDATE
                else
                    OnUpdateCheckFinished?.Invoke(this, null);
```
> https://github.com/goatcorp/FFXIVQuickLauncher/tree/caa764d8deed965ee6549afb3ff7a50ab399b783/XIVLauncher/Settings
```
public static bool IsDisableUpdates => CheckEnvBool("XL_NOAUTOUPDATE");
... System.Environment.GetEnvironmentVariable(var)
```
https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-5.0
> On Windows systems, the environment block of the current process includes:
> All environment variables that are provided to it by the parent process that created it. For example, a .NET application launched from a console window inherits all of the console window's environment variables.

So can sidestep the autoupdate function by going: lutris configure game -> system options -> environmental variable -> add
```
key              |  value
XL_NOAUTOUPDATE  |  true
```

Now launches fine with just a warning about launching as admin.   :)
