### ISSUE TITLE
XIVLauncher warns about missing VC++ runtime under Wine, even though I've installed it

### ISSUE THREAD

**Issue by Maia-Everett** [goatcorp/FFXIVQuickLauncher#502]
**Describe the bug here:**
When I try to launch FFXIV via XIVLauncher with in-game plugins enabled, the launcher complains about the missing Visual C++ 2015-2019 runtime, even though I've installed it — first with `winetricks` and then, after that didn't affect XIVLauncher, with the Microsoft installer linked from the XIVLauncher FAQ.

I have installed .NET Framework 4.8 with `winetricks dotnet48`.

My wineprefix is 64-bit. I use regular wine-staging, not Lutris. Except for this issue, XIVLauncher works correctly, the game does start and Steam correctly shows it as running.

**Steps to reproduce the bug:**
Example:
```
1. Install vcrun2019 with `winetricks vcrun2019`.
2. Start XIVLauncher.
3. Launch the game.
```

**Expected behavior**
Plugins should be enabled in-game.

**Screenshots**
![image](https://user-images.githubusercontent.com/10684/128594529-fc77eb8b-75e0-4d90-98d9-e858e7d02d6b.png)

**Other information (*please* complete the following information):**
  Operating System: Ubuntu 21.04 (64-bit)
  XIVLauncher version: 6.0.4.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled: None yet

**Additional information**

**Comment by reiichi001** [comment]
XIVLauncher requires `dotnet48` (for the launcher) and `vcrun2019` for Dalamud (the plugin system). 

There is a bug with winetricks on some platforms where one or both will fail to install. Since you're getting an XIVLauncher error window, we can be pretty certain that `dotnet48` installed fine, so this is most definitely a case of `vcrun2019` not being installed correctly.

You have a few options:
1. First try to update winetricks.
`winetricks --self-update`
NOTE: You may need to open a bash shell from Lutris, as it provides its own copy of winetricks. Alternatively, you can use your system's winetricks as long as it's pointed to the right prefix.

2. Manually install vcrun2019, ignoring hashes. See https://github.com/Winetricks/winetricks/issues/1770 for more details
```
cabextract -q vc_redist.x86.exe
cabextract -q vc_redist.x64.exe
winetricks --force vcrun2019
```

3. Install vcrun2015 (it's basically the same as 2019 in this context)
`winetricks vcrun2015`

**Comment by Maia-Everett** [comment]
The `vcrun2015` install failed under my wineprefix and also made it unusable, making every Wine app return exit code 53.

I tried a clean wineprefix with `winetricks dotnet48` and `winetricks vcrun2015`, and that solved this particular issue, so it looks like the problem was in my wineprefix being messed up somehow. Instead, however, I got issue #467. Looks like injection with recent Wine versions is still broken.

Closing this issue since it's not an XIVLauncher problem. Thanks for the help!
