### ISSUE TITLE
Build-in Authenticator

### ISSUE THREAD

**Issue by Pinogic** [goatcorp/FFXIVQuickLauncher#531]
Since we can use any kind of Software Authenticator is it possible to build-in the authenticator instead of the Smartphone/Home-Network thing? (the Google Authenticator code is open source)

Actually I am sure many people use already winauth.github.io  (with Strg+C to copy). The only reason why people use this stupid OTP is not the security, its the free travel favorite ingame.

in 2021 "my account was hacked" is the synonym of people who share passwords :D there is no security needed.

**Comment by reiichi001** [comment]
See our development comments on https://github.com/goatcorp/FFXIVQuickLauncher/pull/437 on why we are against this.

You're free to use Authy or another desktop OTP client of your choice if you want to pull up an OTP on the same machine.

**Comment by Kennochas** [comment]
> See our development comments on #437 on why we are against this.
> 
> You're free to use Authy or another desktop OTP client of your choice if you want to pull up an OTP on the same machine.

Frankly, let the user make that decision. You are already storing the password which is arguably the same exact thing, you are bypassing a level of a the security model.

You can store the credential in the windows credential store, which would in turn ensure that the code only works on that machine, if somehow the credential did get exposed.

**Comment by reiichi001** [comment]
The compromise was to allow for a desktop build of xl-auth. 

You're free to make use of other external methods as well, as noted in https://gist.github.com/kensykora/b220573b4230d7622c5a23a497c75fd3 .

It's never coming to XL as a built in feature. Sorry not sorry.

**Comment by Kennochas** [comment]
> The compromise was to allow for a desktop build of xl-auth.
> 
> You're free to make use of other external methods as well, as noted in https://gist.github.com/kensykora/b220573b4230d7622c5a23a497c75fd3 .
> 
> It's never coming to XL as a built in feature. Sorry not sorry.

Your decision makes no sense and is made in feelings and ignorance as opposed to rational design decisions.

**Comment by reiichi001** [comment]
It's not going to happen. You won't change my mind. You won't change Goat's mind. You won't change the other core devs' minds.

Multiple workarounds have been provided. I hope your day is going as well as your temperament.

**Comment by OddSquirrel** [comment]
Just look at how SE as the only company I've come across forces you to enter your password _manually_ during the registration process instead of letting you paste a complicated 30 character one from a secure password app. Most will thus just enter something like `password1234!?` and be done with it. Great job. Not.

This is basically the worst thing in the security world. Make security a dreadful, cumbersome and patronizing experience, and all you gain is users constantly fighting it. Not even my bank makes me jump through such hoops when I log into my account.

Unfortunately, this decision will only make people turn away from 2FA altogether. No idea why somebody really interested in safety would go by the letter of security and at the same time ignore the very spirit of it.

I appreciate your work, it's your work and your decision. Just please don't state that the decision was out of security concerns when it really destroys it. Which is completely ok if that's your aim, it's your project, after all.

**Comment by Kennochas** [comment]
My temperament is just fine.

It just doesn't make any sense, and is trivial to refute. What your tool already offers a bypass that effectively disables the 2nd Factor Square enix has designed.

Why are you okay with removing one factor, but not the other? What is the fundamental difference between them? If the stance is you wish to protect the integrity of the solution, you should not accept storing passwords either.

The three factors of authentication build upon each other. When you remove one of them, you weaken all of them. You cannot in good faith make the argument that storing the password is acceptable, but being able to generate a OTP is not. Its fundamentally flawed.

**Comment by goaaats** [comment]
I feel like our message here got a bit lost over time, in my POV it's mostly from a complexity standpoint as I'm trying to slim down XL and there already is a good way to achieve this with the app, shell scripts, whatever works for you. Maybe we'll reconsider this for our upcoming rewrite.

As a side note, SE is working on a feature that allows you to persist sessions, I'm fairly certain we'll be able to adapt that.
