### ISSUE TITLE
FFXIVLauncher working on Mac OS Big Sur via Crossover!

### ISSUE THREAD

**Issue by seathasky** [goatcorp/FFXIVQuickLauncher#541]
Not much to say other than I was able to get the XIVLauncher to work with a Crossover FF14 client on Mac OS.
**(THIS IS NOT THE MAC OS FF14 GAME CLIENT, IT'S A CUSTOM CLIENT WITHIN CROSSOVER, BUT STILL TECHNICALLY A MAC LICENSE)**

Video here showcasing FF14 via crossover huge performance increase  vs the FF14 Mac client + XIVLauncher working:
https://www.youtube.com/watch?v=wqkvGeVmQGI

Also a screenshot incase you dont want to watch the video:
![nzdt0px](https://user-images.githubusercontent.com/17598024/133922656-da52b0a5-d8e0-4ebc-adb8-ade739f5c90e.png)

**Things not working:**
In game plugins.

I was told that there was no hope for the Mac version of this, but with a little effort from the devs, i'm sure you guys could get plugins working too! 
All I did was make a new Windows 10 Bottle w/ Crossover, installed DXVK, Direct X and .NET + C++, installed the launcher within the bottle and it worked!

**Other details:** 
Crossover still flags the client as a Mac Client probably because of DXVK, so you have to use a Mac license regardless if it's running through crossover or not. Not sure how this affects XIVLauncher with injection for plugins to work.

Would love to see the in-game features working on Mac as well! Thanks!

**Comment by reiichi001** [comment]
While I commend your efforts, this is old news. (See my posts in Discord about this). There should be little to no performance differences given that the "Official Mac Client" is quite literally just CrossOver for Mac wrapped up into a single release for the user. (So if anything, the custom build of Wine might be a little out of date, but this is likely not a major factor).

CrossOver does not provide support for Hide Wine Exports. It will always require a Mac platform on the service account.

We purposely aren't providing support for the Mac client because attempting to support plugins is not worth the trouble of attempting to sort out CrossOver's somewhat proprietary changes. And because a user would have to buy CrossOver in addition to the Mac client just to be able to play. (Just use BootCamp. Or Linux.)

**Comment by seathasky** [comment]
As

> While I commend your efforts, this is old news. (See my posts in Discord about this). There should be little to no performance differences given that the "Official Mac Client" is quite literally just CrossOver for Mac wrapped up into a single release for the user. (So if anything, the custom build of Wine might be a little out of date, but this is likely not a major factor).

You may think that but you arent factoring in that the Mac native client DOES NOT support esync or at least doesnt have it enabled. Through crossover you can enable this and you see in insane performance increase. 
Proof here:
![t8iCZJc](https://user-images.githubusercontent.com/17598024/133937505-ef76be7d-0d7b-4f8f-860c-0bc024be0446.png)
This is with 4k textures enabled and on high settings in game. You cant tell me the mac client every got this high fps :)

Anyways, as far as plugins go, i'll cut my losses. At least my client runs closer to the windows 10 client. That's all I can ask for.
