### ISSUE TITLE
Gshade does not work with this launcher

### ISSUE THREAD

**Issue by TrueZangon** [goatcorp/FFXIVQuickLauncher#545]
Unable to open the gshade window in game when launching through this launcher. I've confirmed it still works if I launch ff14 normally. I've set gshade to attached to the launcher but it still does not work.

**Comment by reiichi001** [comment]
Are you sure that you have the correct gamepath set in XIVLauncher? Or did you end up reinstalling the game? (If XIVLauncher downloaded 45-65GB of patches, you've installed the game again).

Otherwise, which gshade injection method are you using? And have you tried one of the alternatives? (DXGI, D3D11, or DINPUT8). If you're not sure, head to `<your FFXIV install folder>\game` and check for one of more of the dll files:
- dxgi.dll (default)
- d3d11.dll (alternate)
- dinput8.dll (second alternate)

If you have more than one of them, delete the extras. You can freely rename it to switch versions, or you can run the gshade installer again.

**Comment by TrueZangon** [comment]
Mentioning the 45-65GB patch tipped me off, it looks like it downloaded a second copy of FF14 to another hard drive for some reason. I've got it pointing to the correct one and it is working now, thank you for assisting!
