### ISSUE TITLE
Game loads, but it keeps loading on a black screen, then crash

### ISSUE THREAD

**Issue by Izedra** [goatcorp/FFXIVQuickLauncher#570]
At the time I start the game (and I mean the game, not he launcher), it freezes, then crash, and throw me this error:

**System.Exception: Game exited prematurely
   en XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) en D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:línea 270
Version: 6.0.9.0
Git Hash: 6.0.9-0-g5113f9e
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn**

This only happens if I open the game for a second time after booting up the computer.

Edit: Seems like it happens with the normal launcher too, so it could be an error unrelated to the quick launcher. Anyways, I will let this open in case someone else have this issue related to the use of the quick launcher.

**Comment by reiichi001** [comment]
If this was happening with the official launcher too, it was likely being caused by corrupted client files. This can happen if you've ever used Textools.

If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue or contact us in discord and we can help troubleshoot it.
