### ISSUE TITLE
Suspicions logon hold on my account after usage. 

### ISSUE THREAD

**Issue by screwystein** [goatcorp/FFXIVQuickLauncher#589]
**Describe the bug here:**
Recently installed this so I could utilized some of the add-ons. About a day after this My account had a password hold on it due to suspicious logon attempts.  I enjoy using your software; just want to make sure the program is secure with my credentials. 

**Steps to reproduce the bug:**
Example:
```
1. Logged in
2. No unexpected behavior. 
3. Account locked out after attempting to log in once more. 
```

**Expected behavior**
Would appreciate some clarification on stored credentials. 

**Screenshots**
Example:

![se email](https://user-images.githubusercontent.com/24358202/142336114-c6c4ee2f-6467-48d3-a07d-9b1f4012162e.png)
Sensitive info has been redacted. 

**Other information (*please* complete the following information):**
  Operating System: Win 10
  XIVLauncher version: Latest
  Launching as admin?: Yes
  Using Steam?: No
  Addons/Plugins enabled: Simple Tweaks

**Additional information**

**Comment by goaaats** [comment]
Hey, this can happen since XIVLauncher counts as a "new PC" to Square Enix, and they tend to force password resets based on heuristics if you switch PCs very quickly.
If you reset your password and downloaded XIVLauncher from its [official page](https://github.com/goatcorp/FFXIVQuickLauncher/releases/tag/6.0.17), everything should be back to normal.

Here's a FAQ entry on XIVLauncher safety: https://goatcorp.github.io/faq/xl_troubleshooting#q-are-xivlauncher-dalamud-and-dalamud-plugins-safe-to-use

**Comment by screwystein** [comment]
Hey! thanks for the quick update on this. 
I know its not quite a bug but i appreciate the information none the less. 
You can close the issue as my questions have been answered. If i run into any more issues I'll be sure to contact yall here. 

Thanks again!
