### ISSUE TITLE
Screenshots broken again...

### ISSUE THREAD

**Issue by thecoint** [goatcorp/FFXIVQuickLauncher#683]
can anyone help with my screenshot issue, the launcher and game files have been set as exception in avast but i still cant take screenshots. what doesn't make sense to me is that i can take screenshots in the normal ff14 launcher. just not when i launch the game through XIV launcher.
I was also able to take screenshots for the last  week after one update but then after the newest update they stop working again.

**Comment by reiichi001** [comment]
This usually indicated botched file permissions. Like if the official launcher or game exe was set to run as admin. (Even if just a shortcut was and you used that).

If it's just screenshots, you can try putting in a new screenshot file location in your FFXIV system settings. Otherwise, you'll need to address the file permission issue (most likely, your user no longer owns / has "full control" over the `Documents\My Games\Final Fantasy XIV - A Realm Reborn\screenshots` folder.

**Comment by thecoint** [comment]
I've already tried changing the file for screenshots but that dosent work either. I had a screenshot problem before but an update fixed it then the new one came out and it broke it.
