### ISSUE TITLE
Dalamud will not up date and stuck 

### ISSUE THREAD

**Issue by AlexisBliss** [goatcorp/FFXIVQuickLauncher#776]
hey i hope i can get some assistance here ive been hard stuck here trying to get the launcher to work again after this randomly started to happen the other day it was working perfectly the day before also a few ours prior i have tried everything thats been suggested to me in the discord but to no avail so figured this is my last option.

so upon launching the launcher it looks all fine, i then press log in and im faced with this 
https://gyazo.com/5e98ad4572bbdd97a29d26ab4149493d

after liek 30mins-hour it will boot the gaem i get excited and there is no dalamud and the /xldev or /xlhelp doesnt work and when i press escape to bring the menu up there is normally dalamud plugin which also isnt there.

also as you can see i have both xiv launcher and the original launcher whitelisted
https://gyazo.com/f9a95c74f8c1d7b2e8326e72854c3850
https://gyazo.com/d2a279ff585cedc94fca17234d217b2e

i also have them in the exclusion section aswell 
https://gyazo.com/d35c393cba8a087d36c205a026b8f025

and yet im still faced with the same issue and nothing seems to be fixing it.

i even went as far as to do a fresh complete install of both launchers and still nothing 
upon downloading the setup.exe of the site as it instructions say this what i have
https://gyazo.com/6b5666567bc7f509c50d724d41f5c254

now when i check in the files there is no dalamud.dll anywhere so not sure on how it can update something that is not there. i really hope this can be resolved as i enjoy the Quality of life this brings.

also below is the output.log and the launcher configV3 screenshot 
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8309444/output.log)
https://gyazo.com/18b688b0a83fd71d747e0b4812a96455

i thank you kindly for going over all this in advance

**Comment by AlexisBliss** [comment]
this is still persistent after the patch update

**Comment by KlownHorn** [comment]
I'm having this exact same issue as of a couple days ago.

**Comment by KlownHorn** [comment]
This issue appears to be Dalamud being unable to handle instability in folks's internet. I experience micro disconnects on occasion which apparently is enough to make Dalamud shit itself and die when updating itself or the asset folder rather than just resuming the download afterward. If you are in an area with spotty coverage you might be screwed considering the silence on this issue outside of "fix your internet" on the discord. 

If you're on a laptop try visiting a place with a more stable connection for a bit and updating there. If you're on wireless, try plugging in for a little bit just to update. A long ethernet cable is pretty cheap and you don't have to leave it plugged in if its running through the middle of your home to get to your PC. This was my solution. Otherwise there's not much you CAN do. Crazy that we can pretty comfortably play the game on our "broken" internet connection but we can't download a 30MB asset folder :).

**Comment by goaaats** [comment]
We're using standard Windows APIs for downloads and Cloudflare as a CDN, if your internet can't handle that, it's definitely not on us, seeing as it works for everyone else

**Comment by KlownHorn** [comment]
19 days without a response to this, but after a bit of criticism the thread gets one in under an hour.

For what its worth I don't think its your job to deal with my spotty internet connection and I appreciate you offering any form of tech support at all for an incredibly useful tool you've provided to 14 players for free so I'm sorry about being rude, was just frustrated with the silence on this thread and thought it might provoke a reply. 

I'm not going to pretend I know a thing about APIs but its still strange to me that I can play 14, download 50gb steam games, and download files from file sharing sites mostly without issue but Dalamud can't seem to update a 30mb asset folder. Maybe its a problem with the Windows API or Cloudflare or something but it feels like it should be able to pick up again after a disconnect rather than hanging for 20 minutes and then giving up. 
If there's nothing you can do about that however, then this suggestion https://github.com/goatcorp/FFXIVQuickLauncher/issues/700 could help folks pinpoint whether the download is being entirely blocked by antivirus or firewall, in that the bar would stop at the same place or not fill at all, while folks with my and Alexis's issue would probably see it stop at different spots whenever a disconnect happens. That way we could hopefully be able to more easily identify the issue.  

I'm well aware that its a niche problem to fix in a project that's free and fan made though, so I'm not expecting you to jump on it just to help the minority of folks in areas with questionable internet service out, and I appreciate you eventually responding. Just sort of hoping more insight can be provided to people than "fix your internet" or silence in future. Sorry again about being a rude.

**Comment by reiichi001** [comment]
> 19 days without a response to this, but after a bit of criticism the thread gets one in under an hour.

The fastest method to getting support is on out Discord where there are usually multiple support people online + other users familiar with common issues. 

Github issues is not the most ideal place for general "customer support" style inquiries, even with the support templates we have in place, which weren't used here anyways.

Typically, XIVLauncher will attempt to retry downloading assets 10 times. It's not just hanging at a single attempt. That typically indicates that it's failing repeatedly.

Our logs will show when a failure takes place as well, which is generally the first thing we'll ask for on Discord, as we have a friendly bot that will parse the data for quick at-a-glance troubleshooting while someone more familiar with the codebase can check the log in full.

**Comment by goaaats** [comment]
If I don't respond to things, it means that I don't have a solution, and I don't have a solution to this right now.

There's things that are higher priority for me, but I've definitely not been ignoring it - the past few launcher updates saw rewrites/modernization of the code that handles these updates in order to alleviate stuff like this, but in the end all I can do is throw things at the wall and see what sticks since the problem seems very rare and I've never encountered it. Since you're still here I assume these fixes haven't actually helped in this case.

I'm fairly certain that the ball isn't actually in my court, and that it's either an issue with Windows or your network conditions, but in the end it has to work.

**Comment by kaegthegamer** [comment]
For me, after the update, Dalamud doesn't load at all. XIVLauncher works fine, but nothing from Dalamud loads...not even the basic system menu settings
![systemmenu](https://user-images.githubusercontent.com/91478726/163009071-cb7c3c17-2915-4c5c-844c-7ad0e1cfa48d.jpg)
.

**Comment by goaaats** [comment]
The game was updated today. Nothing will work.

**Comment by kaegthegamer** [comment]
Ok thanks for the info. I thought I was doing something wrong.

> The game was updated today. Nothing will work.

**Comment by goaaats** [comment]
I think this should be good/way better now. If it still happens, please post another comment here and I'll reopen.

**Comment by iklier** [comment]
Hit this on a new system [Window 11] and on a previously working system [Steam Deck] and triaged it down to an issue with IPv6. 
Disabling IPv6 on the Windows 11 network interface resolved the issue and disabling DHCPv6 and IPv6 RA on the router resolved it for the Steam Deck.

**Comment by twoblues** [comment]
> Hit this on a new system [Window 11] and on a previously working system [Steam Deck] and triaged it down to an issue with IPv6. Disabling IPv6 on the Windows 11 network interface resolved the issue and disabling DHCPv6 and IPv6 RA on the router resolved it for the Steam Deck.

OH MY GOD THANK YOU THIS HAS BEEN DRIVING ME INSANE FOR LIKE A YEAR. 

I use my phone's hotspot at work sometimes and if I have a poor connection (but completely usable), then Dalamud will forever get stuck on "updating assets." Disabling IPv6 worked for me as well on Windows 10.

**Comment by reiichi001** [comment]
You should not be disabling IPv6. That's a bandaid that will have larger repercussions in the future. 

These are things you should do:
- Contact your ISP and complain about IPv6/DNS6 issues. (good luck getting a support person who can do something about that)
- Try setting a third party DNS6 provider, like Google or CloudFlare (you can use their IPv4 DNS too if you want, but it's not strictly needed)
- Try using a VPN like CloudFlare Warp or ProtonVPN to see if that works instead.

**Comment by twoblues** [comment]
> You should not be disabling IPv6. That's a bandaid that will have larger repercussions in the future.
> 
> These are things you should do:
> 
> * Contact your ISP and complain about IPv6/DNS6 issues. (good luck getting a support person who can do something about that)
> * Try setting a third party DNS6 provider, like Google or CloudFlare (you can use their IPv4 DNS too if you want, but it's not strictly needed)
> * Try using a VPN like CloudFlare Warp or ProtonVPN to see if that works instead.

Yeah, I've done 2 and 3 before in the past and it has not helped when this scenario crops up. I'll admit I haven't tried Cloudflare Warp, but I've used my usual VPN (Windscribe) and it didn't make a difference.

Calling xfinity about the quality/speed of the Verizon towers during peak hours in the city is probably not a valid solution. Nonetheless, it is something I've complained about to them in the past. There is nothing that can be in that case other than them giving me monthly credits on my bill.

**Comment by KrispyKrisp9000** [comment]
Dalamud tries to update core like 4-5 times each getting to 100%, then it tells you check anti-virus even though it's been added to exceptions, and it still not update core, so can't use plugins O.o
